### ISSUE TITLE
Doc should be a directory, not a branch!

### ISSUE THREAD

**Issue by ugurdogrusoz** [NuruNabiyev/1F.Cerebrus#3]
You should have 2 branches: master (default) + unstable
doc is a directory in each of these branches for reports, not a branch itself!

**Comment by NuruNabiyev** [comment]
Did it. We also decided to change the name of the game ¯\_(ツ)_/¯

**Comment by ugurdogrusoz** [comment]
@NuruNabiyev great thanks. When you resolve an issue though, you should assign it back to the creator (keep in mind for next time).
